export const treeRootId = 1;
export const initialTree = {
  0: {
    id: '0',
    name: 'x',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  1: {
    id: '1',
    name: 'জহির উদ্দিন পাটোয়ারি',
    type: 'input',
    children: ['2','3'],
    siblings: [],
    spouses: [],
  },
  2: {
    id: '2',
    name: 'কোকাই মোল্লা',
    type: 'input',
    children: ['4', '5', '6', '7'],
    siblings: [],
    spouses: [],
  },
  3: {
    id: '3',
    name: 'আমানুদ্দিন মোল্লা',
    type: 'input',
    children: ['8', '9', '10', '11'],
    siblings: [],
    spouses: [],
    // isSibling: true,
  },
  4: {
    id: '4',
    name: 'মোহাম্মদ আলী মোল্লা',
    type: 'input',
    children: ['12'],
    siblings: [],
    spouses: [],
  },
  5: {
    id: '5',
    name: 'আহমদ আলী মোল্লা',
    type: 'input',
    children: ['13', '14', '15', '16'],
    siblings: [],
    spouses: [],
  },
  6: {
    id: '6',
    name: 'রঞ্জন আলী মোল্লা',
    type: 'input',
    children: ['17', '18', '19', '20', '21'],
    siblings: [],
    spouses: [],
  },
  7: {
    id: '7',
    name: 'ফজর আলী মোল্লা',
    type: 'input',
    children: ['22', '23', '24'],
    siblings: [],
    spouses: [],
  },
  8: {
    id: '8',
    name: 'ওহীদ আলী মোল্লা',
    type: 'input',
    children: ['25', '26', '27', '28'],
    siblings: [],
    spouses: [],
  },
  9: {
    id: '9',
    name: 'হাদর আলী মোল্লা',
    type: 'input',
    children: ['29', '30'],
    siblings: [],
    spouses: [],
  },
  10: {
    id: '10',
    name: 'সাদক আলী মোল্লা',
    type: 'input',
    children: ['31', '32', '33', '34', '35'],
    siblings: [],
    spouses: [],
  },
  11: {
    id: '11',
    name: 'সৈয়দ আলী মোল্লা',
    type: 'input',
    children: ['36', '37', '38'],
    siblings: [],
    spouses: [],
  },
  12: {
    id: '12',
    name: 'ইউনুস মুন্সি',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  13: {
    id: '13',
    name: 'আকুবালী মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  14: {
    id: '14',
    name: 'অছিমুদ্দিন মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  15: {
    id: '15',
    name: 'ইউসুফ আলী মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  16: {
    id: '16',
    name: 'আয়ুব আলী মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  17: {
    id: '17',
    name: 'চিঠাগাজী মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  18: {
    id: '18',
    name: 'এবাদ আলী মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  19: {
    id: '19',
    name: 'ছায়দ উল্ল্যাহ মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  20: {
    id: '20',
    name: 'জবেদ আলী মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  21: {
    id: '21',
    name: 'আবুল হাশেম মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  22: {
    id: '22',
    name: 'ইব্রাহীম তপাদার মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  }, 
  23: {
    id: '23',
    name: 'ছিদ্দিক আলী মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  24: {
    id: '24',
    name: 'সুলতান মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  }, 
  25: {
    id: '25',
    name: 'ইয়াছিন মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  26: {
    id: '26',
    name: 'কালা মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  27: {
    id: '27',
    name: 'খলিল মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  28: {
    id: '28',
    name: 'অলিমুদ্দিন মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  29: {
    id: '29',
    name: 'ছেরাজল হক মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  30: {
    id: '30',
    name: 'জালালুদ্দিন মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  31: {
    id: '31',
    name: 'আঃ আজিজ মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  32: {
    id: '32',
    name: 'জয়নাল আবদিন মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  33: {
    id: '33',
    name: 'আঃ মতিন মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  34: {
    id: '34',
    name: 'আবুল হোসেন মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  }, 
  35: {
    id: '35',
    name: 'আনোয়ার হোসেন মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  36: {
    id: '36',
    name: 'আঃ আজিদ মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  37: {
    id: '37',
    name: 'আঃ রহমান মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
  38: {
    id: '38',
    name: 'আঃ গফুর মোল্লা',
    type: 'input',
    children: [],
    siblings: [],
    spouses: [],
  },
};
